### PR TITLE
Added Notebook to correct spot

### PR DESCRIPTION
**Pull request by tthatcher95**
Notebook was in PyHAT. It will not be in this repo.

### CODE REVIEW

**Comment by tthatcher95** [comment]
@egaultUSGS Please review this, and merge it. Thank you!

**Comment by jlaura** [comment]
Why is this in this repository? I see one bayleef import in the notebook that is never used. This is making use of PyHAT (which is why it is/was in PyHAT?).

**Comment by Kelvinrr** [comment]
It relies on Bayleef for creating the database that it uses for processing. It doesn't use PyHat at all. At the time PyHat (still PySat at the time) was too unstable to use and it was easier to use the approach we used here of just using the DB tables directly as DataFrames. I think I was gonna move them into PyHat but decided to spend time trying to teach Greg how to use what's already their instead.

I don't think it matters where the notebook is, for now, leaving it in PyHat is fine.

**Comment by egaultUSGS** [comment]
I'm having some difficulties with conda when attempting to install bayleef from a local file. Is there a conda channel that may have access to it? Otherwise, placing the notebook in the same directory as the provided bayleef file is the only way I can get things running.

**Comment by Kelvinrr** [comment]
I can help you out later today if you're still coming in. As far as this PR is concerned I think I'll just merge it. Until this stuff is integrated into PyHat anyways in which case it'll go away.

**Pull request merged**
